### ISSUE TITLE
请问怎么使用认证鉴权功能，有文档吗，还有其他的一些功能文档里也没有看到了

### ISSUE THREAD

**Issue by leogoing** [hango-io/hango-gateway#20]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by ethanhanjiahao** [comment]
感谢 @leogoing 的关注。当前hango的版本beta中。我们在内部实践的认证使用jwks结合envoy jwt的能力进行实践；在和外部系统对接，更多采用external_auth。后续的hango版本我们会推出来。

**Comment by wbpcode** [comment]
社区外部认证相关文档：
https://www.envoyproxy.io/docs/envoy/latest/configuration/http/http_filters/ext_authz_filter
社区 jwt 认证相关文档：
https://www.envoyproxy.io/docs/envoy/latest/configuration/http/http_filters/jwt_authn_filter

目前，beta 版本的 hango 的控制台还没有开放该能力。

**Comment by ethanhanjiahao** [comment]
> 社区外部认证相关文档： https://www.envoyproxy.io/docs/envoy/latest/configuration/http/http_filters/ext_authz_filter 社区 jwt 认证相关文档： https://www.envoyproxy.io/docs/envoy/latest/configuration/http/http_filters/jwt_authn_filter
> 
> 目前，beta 版本的 hango 的控制台还没有开放该能力。

@wbpcode 我建一个roadmap，我们跟进下。https://github.com/hango-io/hango-gateway/issues/21

**Comment by ethanhanjiahao** [comment]
后续我们通过 https://github.com/hango-io/hango-gateway/issues/21  跟进
