### ISSUE TITLE
hango是否支持证书管理和HTTPS配置

### ISSUE THREAD

**Issue by ytwang0320** [hango-io/hango-gateway#50]
hango是否支持证书管理和HTTPS配置

**Comment by trickMin** [comment]
目前版本还不支持HTTPS能力，在后续版本中会逐步规划，HTTPS能力在v2.2.0版本将得到支持，具体可以参考我们的RoadMap: https://hango-io.github.io/website/getting-started/roadmap/roadmap-2023/
